### ISSUE TITLE
Create a Navigation node layout

### ISSUE THREAD

**Issue by KeiferE-zz** [uvic-auvic/polaris_2018#49]
***MIGRATED FROM REDHERRING REPO***

The motor controller is only used to tell the motors exactly what to do (enable motor at RPM X). The motor controller controller will recieve input from the AI on where to go (xyz position). Based on the position it will create a connection with the cameras/peripherals themselves and course-correct by re-adjusting the motors.

**Comment by lymacasm** [comment]
Idea: Navigation requests come from AI, sent to control system node. Control system node looks at IMU and depth sensors to try and produce vectors using error feedback. Control system sends its vectors to Thrustmap which maps the vectors into thruster outputs. These can then be directly set to thrusters using the motor controller node. 

IMU linear velocity error can grow at t^2. To correct for this, cameras should also try and approximate linear velocity. When they have determined velocity, that velocity should be sent directly to the IMU so that it can correct its current velocity vector.

**Comment by lymacasm** [comment]
Code implementing this has been merged in #132
